name: Deploy Staging Frontend
 
on:

  push:

    branches: [ "staging" ]
 
jobs:

  deploy:

    if: github.event_name != 'pull_request'

    runs-on: ubuntu-latest
 
    steps:

      - name: Deploy to STAGING server

        uses: appleboy/ssh-action@v1.2.2

        with:

          host: ${{ secrets.STAGING_HOST }}

          username: ${{ secrets.STAGING_USERNAME }}

          key: ${{ secrets.STAGING_SSH_KEY }}

          port: 22

          script: |

            echo "Deploying to STAGING..."
 
            cd ~/projects/staging-dr-app/frontend
 
            export NVM_DIR="$HOME/.nvm"

            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
 
            git pull origin staging

            npm ci

            npm run build
 
            pm2 reload ecosystem.config.js --env staging
 